In [ ]:
#NUMPY

In [7]:
a = [1,2,3,4]
b = [2,3,4,5]

In [9]:
ab = []

In [11]:
for i in range(0, len(a)):
    ab.append(a[i]*b[i])

In [13]:
ab

[2, 6, 12, 20]

In [15]:
import numpy as np

In [17]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [19]:
a * b

array([ 2,  6, 12, 20])

In [21]:
#NumPy array i oluşturmak

In [23]:
import numpy as np

In [27]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
a = np.array([1,2,3,4,5])

In [31]:
type(a)

numpy.ndarray

In [33]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [35]:
#Sıfırdan Array Oluşturma

In [37]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [47]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [49]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
np.random.normal(10,4,(3,4))

array([[14.19591   ,  7.0174137 , 25.12853417, 10.66103275],
       [ 9.49214773, 15.97717401,  8.18691896, 18.22150552],
       [12.18912413,  9.87843394,  4.5883542 ,  9.4327311 ]])

In [53]:
np.random.randint(0,10,(3,3))

array([[5, 5, 0],
       [2, 9, 2],
       [5, 6, 3]])

In [55]:
import numpy as np

In [57]:
np.random.randint(10, size = 10)

array([2, 8, 3, 2, 0, 2, 7, 4, 4, 7])

In [65]:
a = np.random.randint(10, size = 10)

In [67]:
a.ndim

1

In [69]:
a.shape

(10,)

In [71]:
a.size

10

In [73]:
a.dtype

dtype('int32')

In [75]:
b = np.random.randint(10, size = (3,5))

In [77]:
b

array([[7, 4, 9, 9, 4],
       [4, 1, 5, 1, 3],
       [1, 5, 6, 1, 3]])

In [79]:
b.ndim

2

In [81]:
b.shape

(3, 5)

In [83]:
b.size

15

In [85]:
b.dtype

dtype('int32')

In [87]:
#Yeniden Şekillendirme (Reshaping)

In [89]:
import numpy as np

In [93]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a

array([3, 1, 0, 7, 8, 6, 9, 8, 6, 7])

In [101]:
a.ndim

1

In [ ]:
b = a.reshape((1,9))

In [109]:
b.ndim

2

In [112]:
#Array Birleştirme (Concatenation)

In [114]:
import numpy as np

In [116]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [118]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [120]:
z = np.array([7,8,9])

In [122]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
#İki Boyut

In [126]:
a = np.array([[1,2,3],
              [4,5,6]])

In [128]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [130]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [132]:
#ARRAY AYIRMA ( SPLİTTİNG )

In [134]:
import numpy as np

In [136]:
x = np.array([1,2,3,99,99,3,2,1])

In [140]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [142]:
a,b,c = np.split(x, [3,5])

In [144]:
a

array([1, 2, 3])

In [146]:
b

array([99, 99])

In [148]:
c

array([3, 2, 1])

In [150]:
#İki Boyutlu Ayırma

In [152]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [154]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [156]:
ust ,alt = np.vsplit(m,[2])

In [158]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [160]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [162]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [164]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [166]:
sag ,sol = np.hsplit(m,[2])

In [168]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [170]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [172]:
#ARRAY SIRALAMA

In [174]:
import numpy as np

In [176]:
v = np.array([2,1,4,3,5])

In [178]:
v

array([2, 1, 4, 3, 5])

In [180]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [182]:
v

array([2, 1, 4, 3, 5])

In [184]:
v.sort()

In [186]:
v

array([1, 2, 3, 4, 5])

In [188]:
#İki boyutlu array sıralama

In [190]:
m = np.random.normal(20,5, (3,3))

In [192]:
m

array([[19.47800029, 14.23821187, 16.55554078],
       [27.05841781, 17.16504348, 18.34520588],
       [15.93449544, 23.28031028, 21.36491423]])

In [194]:
np.sort(m, axis = 0)

array([[15.93449544, 14.23821187, 16.55554078],
       [19.47800029, 17.16504348, 18.34520588],
       [27.05841781, 23.28031028, 21.36491423]])

In [196]:
#İNDEX İLE ELEMANLARA ERİŞMEK

In [198]:
import numpy as np
a = np.random.randint(10, size =10)
a

array([7, 7, 4, 1, 1, 2, 3, 6, 2, 7])

In [200]:
a[0]

7

In [202]:
a[-1]

7

In [204]:
a[0]= 100

In [206]:
a

array([100,   7,   4,   1,   1,   2,   3,   6,   2,   7])

In [208]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 8, 3, 4, 1],
       [4, 8, 2, 5, 5],
       [2, 9, 7, 7, 7]])

In [210]:
m[0,0]

3

In [212]:
m[1,1]

8

In [214]:
m[1,4] = 99

In [216]:
m

array([[ 3,  8,  3,  4,  1],
       [ 4,  8,  2,  5, 99],
       [ 2,  9,  7,  7,  7]])

In [218]:
m[1,4] = 2.2

In [220]:
m

array([[3, 8, 3, 4, 1],
       [4, 8, 2, 5, 2],
       [2, 9, 7, 7, 7]])

In [222]:
#SLİCİNG İLE ELEMANLARA ERİŞMEK (ARRAY ALT KÜMESİNE ERİŞMEK)

In [224]:
import numpy as np

In [228]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [230]:
a[0:3]

array([20, 21, 22])

In [232]:
a[:3]

array([20, 21, 22])

In [234]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [236]:
a[1::2]

array([21, 23, 25, 27, 29])

In [238]:
a[2::2]

array([22, 24, 26, 28])

In [243]:
a[2::3]

array([22, 25, 28])

In [245]:
#İki boyutlu slice işlemleri

In [247]:
m = np.random.randint(10, size = (5,5))

In [249]:
m

array([[3, 0, 7, 8, 3],
       [2, 9, 0, 9, 6],
       [8, 6, 5, 7, 5],
       [5, 5, 4, 5, 3],
       [3, 4, 9, 2, 2]])

In [251]:
m[:,0]

array([3, 2, 8, 5, 3])

In [253]:
m[:,4]

array([3, 6, 5, 3, 2])

In [255]:
m

array([[3, 0, 7, 8, 3],
       [2, 9, 0, 9, 6],
       [8, 6, 5, 7, 5],
       [5, 5, 4, 5, 3],
       [3, 4, 9, 2, 2]])

In [257]:
m[0,:]

array([3, 0, 7, 8, 3])

In [259]:
m[0]

array([3, 0, 7, 8, 3])

In [261]:
m[1,:]

array([2, 9, 0, 9, 6])

In [263]:
m[0:2, 0:3]

array([[3, 0, 7],
       [2, 9, 0]])

In [265]:
m[:,0:2]

array([[3, 0],
       [2, 9],
       [8, 6],
       [5, 5],
       [3, 4]])

In [267]:
m

array([[3, 0, 7, 8, 3],
       [2, 9, 0, 9, 6],
       [8, 6, 5, 7, 5],
       [5, 5, 4, 5, 3],
       [3, 4, 9, 2, 2]])

In [269]:
m[1:3, 0:2]

array([[2, 9],
       [8, 6]])

In [271]:
#ALT KÜME ÜZERİNDE İŞLEM YAPMAK

In [273]:
import numpy as np

In [275]:
a = np.random.randint(10, size =(5,5))
a

array([[0, 0, 9, 5, 8],
       [9, 4, 6, 2, 9],
       [0, 7, 0, 6, 2],
       [6, 7, 1, 3, 9],
       [0, 5, 2, 7, 9]])

In [277]:
alt_a = a[0:3, 0:2]
alt_a

array([[0, 0],
       [9, 4],
       [0, 7]])

In [279]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [281]:
alt_a

array([[99999,     0],
       [    9,   888],
       [    0,     7]])

In [283]:
a

array([[99999,     0,     9,     5,     8],
       [    9,   888,     6,     2,     9],
       [    0,     7,     0,     6,     2],
       [    6,     7,     1,     3,     9],
       [    0,     5,     2,     7,     9]])

In [285]:
m = np.random.randint(10, size =(5,5))
m

array([[8, 1, 6, 2, 8],
       [7, 5, 8, 8, 0],
       [2, 4, 8, 9, 4],
       [6, 0, 6, 8, 7],
       [0, 9, 0, 3, 0]])

In [287]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[8, 1],
       [7, 5],
       [2, 4]])

In [289]:
alt_b[0,0] = 9999

In [291]:
alt_b

array([[9999,    1],
       [   7,    5],
       [   2,    4]])

In [293]:
m

array([[8, 1, 6, 2, 8],
       [7, 5, 8, 8, 0],
       [2, 4, 8, 9, 4],
       [6, 0, 6, 8, 7],
       [0, 9, 0, 3, 0]])

In [295]:
#FANCY İNDEX İLE ELEMANLARA ERİŞMEK

In [297]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [299]:
v[1]

3

In [301]:
v[3]

9

In [303]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [305]:
al_getir = [1,3,5]

In [307]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [309]:
v[al_getir]

array([ 3,  9, 15])

In [311]:
#İki boyutta fancy

In [313]:
m = np.arange(9).reshape((3,3))

In [315]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [317]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [319]:
m[satir,sutun]

array([1, 5])

In [321]:
#Basit index ile fancy index

In [323]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [325]:
m[0, [1,2]]

array([1, 2])

In [327]:
#Slice ile fancy

In [329]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [331]:
#KOŞULLU ELEMAN İŞLEMLERİ

In [333]:
import numpy as np 

In [335]:
v = np.array([1,2,3,4,5])

In [337]:
v[v<3]

array([1, 2])

In [339]:
v[v > 3]

array([4, 5])

In [341]:
v[v >= 3]

array([3, 4, 5])

In [343]:
v[v <=3 ]

array([1, 2, 3])

In [345]:
v[v == 3]

array([3])

In [347]:
v[v != 3]

array([1, 2, 4, 5])

In [349]:
v

array([1, 2, 3, 4, 5])

In [351]:
v *2

array([ 2,  4,  6,  8, 10])

In [353]:
v/ 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [355]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [357]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [359]:
# MATEMATİKSEL İŞLEMLER

In [365]:
import numpy as np
v = np.array([1,2,3,4,5])

In [367]:
v - 1

array([0, 1, 2, 3, 4])

In [369]:
v * 5

array([ 5, 10, 15, 20, 25])

In [371]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [373]:
v * 5/ 10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [375]:
#ufunc

In [377]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [379]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [381]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [383]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [385]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [387]:
v **3

array([  1,   8,  27,  64, 125], dtype=int32)

In [389]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [391]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [393]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [395]:
np.absolute(np.array([-3]))

array([3])

In [397]:
np.sin(360)

0.9589157234143065

In [401]:
np.cos(180)

-0.5984600690578581

In [403]:
v = np.array([1,2,3])

In [405]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [407]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [409]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\hhati\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\hhati\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [411]:
#İSTATİKSEL HESAPLAMALAR

In [413]:
v

array([1, 2, 3])

In [415]:
np.mean(v)

2.0

In [417]:
v.sum()

6

In [419]:
v.min()

1

In [421]:
#NUMPY İLE İKİ BİLİNMEYENLİ DENKLEM ÇÖZÜMÜ

In [423]:
import numpy as np 

In [425]:
# 5 * x0 + x1 = 12
# x0 + 3*x1 = 10

In [427]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [429]:
a

array([[5, 1],
       [1, 3]])

In [431]:
b

array([12, 10])

In [437]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])